### ISSUE TITLE
Media URL

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#1]
In the response of `/Shop/ShopView` properties `logo` and `photo` have local filesystem path instead of public url.
Please refer to [Shop doc](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/shop.md) and [Media Doc](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/media-type.md) for further information.

**Comment by nicholaslambertucci-ett** [comment]
Same problem on `icon` property of `/api/Service` endpoint

**Comment by jaim23mf** [comment]
Need to know where to upload the files. 

All upload are the same.

**Comment by nicholaslambertucci-ett** [comment]
Is there any endpoint / route to download the uploaded file?

**Comment by jaim23mf** [comment]
No , I just did the upload of the file and return the url when asked.

**Comment by nicholaslambertucci-ett** [comment]
Here you can find a very simple implementation for converting local filesystem path to url:
[0001-Changes-for-return-public-url-of-uploaded-files.patch](https://github.com/jaim23mf/API_eroma2/files/10308707/0001-Changes-for-return-public-url-of-uploaded-files.patch)

**Comment by jaim23mf** [comment]
Changes made in commit ac531cb
