### ISSUE TITLE
ShopView missing interestIds value

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#10]
The field `interestIds` of the `/Shop/ShopView` endpoint response is empty even if shop has one interest associated.
![image](https://user-images.githubusercontent.com/22095470/209809643-37c9cc3d-7419-488b-9f7c-7cc44de96e4e.png)
![image](https://user-images.githubusercontent.com/22095470/209809744-85c52280-f790-4f63-939e-2be4fa916206.png)

**Comment by jaim23mf** [comment]
Fixed with commit 71485b3
