### ISSUE TITLE
Interest format error

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#11]
In the response of `/api/Interest` the `group` field should contain the value as a string, not a number.
See docs for [Intestest](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/interest.md), [Interest group](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/interest-group.md) and its [schema](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/interest-group-enum.schema.json)

This issue is similat to #2

**Comment by jaim23mf** [comment]
Please refer to https://localhost:7260/api/Interest/InterestMobile

Bug fixed commit a02437c
