### ISSUE TITLE
Date formt error

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#12]
The `firstOpeningDay` field of `/Shop/ShopView`, the `dateRange.from` and `dateRange.to` of `/api/Events` and the `exceptions.[*].dateRange.from` and `exceptions.[*].dateRange.to` fields of `/api/Opening` endpoint responses should have` yyyy-MM-dd` format instead of currently used `yyyy-MM-dd\THH:mm:ss.fff\Z`.
![image](https://user-images.githubusercontent.com/22095470/209838719-f0080a5e-fc00-4f70-9a3c-e6ed920ba92e.png)

Please refer to [Shop ](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/shop.md), [Mall Event](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/mall-event.md), [Exception Opening Hours Rule](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/exception-opening-hours-rule.md), [Date range](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/date-range.md) and [Date](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/date-type.md) docs and its [schema](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/date.type.schema.json)

**Comment by jaim23mf** [comment]
Date format fix in commit 7ba3f42
