### ISSUE TITLE
Event Image url returns 404 Not found

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#13]
After uploading a image in Events, the image url returns 404 Not found.

Related to #1

**Comment by nicholaslambertucci-ett** [comment]
No StaticFiles middleware was configured to serve file inside EventsImg folder.
Use the attached patch to solve the issue
[0003-Fix-EventsImage-download.patch](https://github.com/jaim23mf/API_eroma2/files/10315092/0003-Fix-EventsImage-download.patch)

**Comment by jaim23mf** [comment]
Fixed with patch
