### ISSUE TITLE
Pomotion wrong fields format

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#16]
Field interestIds  format and value is wrong in the response of /api/Promo api endpoint.
Currently they contains the object representative of the entity (interest) associated to the promotion, but it should contain the id of these entity.
![image](https://user-images.githubusercontent.com/22095470/209942491-dbc8782c-5ec9-4e22-b875-6e6a741ab2aa.png)

Please refer to [Promotion](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/promotion.md) entity description

**Comment by jaim23mf** [comment]
Please refer to https://localhost:7260/api/Promo/PromoView for the Mobile app 

This  /api/Promo is for the CMS
