### ISSUE TITLE
ShopType format

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#2]
In the response of `/Shop/Category` endpoint, the type and format of `shopType` shopType is incorrect.
It should be a string with defined values, not a number.
Please refer to [Shop Category doc](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/shop-category.md) and [Shop Type Doc](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/shop-type.md)

**Comment by jaim23mf** [comment]
ShopType is an enum as the Doc tells 

    public enum StoreType {
        foodAndBeverage=1,
        store=2
    }

Do you need an endpoint that returns a string instead the enum?

**Comment by nicholaslambertucci-ett** [comment]
Yes, api must return the label associated to enum value.

[Here](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/shop-type-enum.schema.json) the schema for that type 
```
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://ettsolutions.com/pta/wayfinding/jsonschemas/shop-type-enum.schema.json",
    "title": "Shop type definition",
    "description": "Defines under which group the shop will be displayed",
    "type": "string",
    "minLength": 1,
    "enum": [
        "foodAndBeverage",
        "store"
    ]
}
```

**Comment by jaim23mf** [comment]
new endpoint added /Shop/CategoryM

this will send the correct StoreType
