### ISSUE TITLE
Editing Service problem

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#4]
I was editing a service and after I deleted the content of the `order` field to update its value, application send me to login page.
Below you can find the request 
![image](https://user-images.githubusercontent.com/22095470/209664985-98ece530-88e7-4ff4-9384-093e2e07e6cd.png)
![image](https://user-images.githubusercontent.com/22095470/209665017-a48f3966-6105-4c75-ae72-48b4dd222200.png)

and the response
![image](https://user-images.githubusercontent.com/22095470/209665082-2658233f-0e2f-4adb-82a0-1c2af1119719.png)

**Comment by nicholaslambertucci-ett** [comment]
Same problem on ReachUS editing.

**Comment by jaim23mf** [comment]
Bug Fix on commit c3c1a22
