### ISSUE TITLE
DB Initialization script request

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#5]
Need a script to initialize/create all the record on db that have no "creation" method on frontend side.

- [ ] General Opening Hours
- [ ] Map
- [ ] Users

**Comment by nicholaslambertucci-ett** [comment]
This is a very low priority issue

**Comment by jaim23mf** [comment]
We should also add to the script the USER

**Comment by jaim23mf** [comment]
[startDB.txt](https://github.com/jaim23mf/API_eroma2/files/10319181/startDB.txt)
