### ISSUE TITLE
3D floor editor cannot load gltf file by local filesystem path

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#6]
This issues is related to #1 
`modelUrl` field contains the local filesystem path instead of a the public url

**Comment by jaim23mf** [comment]
I have made the commit to be able to load this file.

I have found an issue while loading the gltf file , because of CORS policy i cannot load the .bin file.

**Comment by nicholaslambertucci-ett** [comment]
The problem was the order of app middleware configuration.
By moving `UseStaticFiles` after `UseCors` in the `Configure` method of `Startup` class issue was solved.

[0002-fix-cors-problem-on-FloorGltf-.bin-file.patch](https://github.com/jaim23mf/API_eroma2/files/10313192/0002-fix-cors-problem-on-FloorGltf-.bin-file.patch)
