### ISSUE TITLE
Map Editor Save problems

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#7]
There're some problems when user click on Save button of Floor 3D editor.
1. The request to the api made by the frontend gives 404 Not Found response
![image](https://user-images.githubusercontent.com/22095470/209788286-72dcddb2-d4c6-4cd6-96ce-acbd7d67746f.png)
this is caused by a wrong route definition on `SaveFloor` action of `Map` controller that is missing the `floorId` route parameter
![image](https://user-images.githubusercontent.com/22095470/209788419-e9841dbf-f864-458d-9c63-4546db6fafa8.png)
number 1. problem is solved by adding such parameter in the above route definition
![image](https://user-images.githubusercontent.com/22095470/209788589-d96c9deb-9b19-4821-8132-e00911106951.png)
2. Where the first problem is solved, another one come out. The same request made by fronted gives 400 Bad Request response
![image](https://user-images.githubusercontent.com/22095470/209788924-1c60815b-39c1-421c-9c0e-a14191244553.png)
The validation message `The attachedShopNodeName field is required` let me think that API is expecting a not empty/null `attachedShopNodeName` property value, but in [docs](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/cms/schemas/floor-nav-point.md) suche e field is not required.

**Comment by jaim23mf** [comment]
Parameter attachedShopNodeName set to optional in commit f8aa382
