### ISSUE TITLE
Opening Hours Format Error

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#8]
In the response of `/api/Opening` the fields `fromWeekDay` and `toWeekDay ` should contain the value as a string, not a number.
See docs for [Opening Hours Rule](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/opening-hours-rule.md),  [Day Opening Hours](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/day-opening-hours.md), [Week Day Type](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/week-day.md) and its [schema](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/types/week-day.type.schema.json)

This issue is similat to #2

**Comment by jaim23mf** [comment]
Fix commited in adc84d6

Please refer to https://localhost:7260/api/Opening/OpeningMobile
