### ISSUE TITLE
ShopView wrong fields format

### ISSUE THREAD

**Issue by nicholaslambertucci-ett** [jaim23mf/API_eroma2#9]
Fields `categoryId` and `subcategoryId` format and value are wrong in the response of `/Shop/ShopView` api endpoint.
Currently they contains the object representative of the entity _(shop-category o r shop-sub-category)_ associated to the shop, but they should contain the id of these entity.
![image](https://user-images.githubusercontent.com/22095470/209809128-9629fbb9-333b-4840-85a0-141e43c0f43c.png)

Please refer to [Shop](https://github.com/ettspa/pta-mixed-wayfinding-cmsappmobile-docs/blob/develop/app-mobile/schemas/shop.md) entity description

**Comment by jaim23mf** [comment]
Bug Fixed commit 71485b3

**Comment by nicholaslambertucci-ett** [comment]
That's graet!
